steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/stego-be/stego-bff-nest-application', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/stego-be/stego-bff-nest-application']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'stego-bff', '--image', 'gcr.io/stego-be/stego-bff-nest-application', '--region', 'asia-northeast1']
images:
  - gcr.io/stego-be/stego-bff-nest-application